apiVersion: v1
kind: Service
metadata:
  name: calculator-service
  labels:
    {{- include "calculator.labels" . | nindent 4 }}
spec:
  selector:
    app: calculator
  type: {{ .Values.service.type }}
  ports:
    - protocol: TCP
      port: {{ .Values.calculatorApi.port }}
      targetPort: {{ .Values.calculatorApi.port }}
      nodePort: {{ .Values.calculatorApiService.nodePort }}