apiVersion: apps/v1
kind: Deployment
metadata:
  name: calculator-deployment
  labels:
    {{- include "calculator.labels" . | nindent 4 }}  
spec:
  {{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "calculator.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "calculator.selectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "calculator.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}    
      containers:
        - name: calculator
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: http
              containerPort: {{ .Values.calculatorApi.port }}
          livenessProbe:
            httpGet:
              path: "{{ .Values.calculatorApi.healthCheckUrl }}"
              port: {{ .Values.calculatorApi.port }}
            initialDelaySeconds: 3
            periodSeconds: 3
            failureThreshold: 2
          env:
            - name: HEALTH_ID
              valueFrom:
                configMapKeyRef:
                  name: calculator-envs
                  key: healthId