apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: calculator-ingress
  labels:
    app: calculator-ingress
    chart: {{ template "calculator.chart" . }}
    release: {{ $.Release.Name }}
    heritage: {{ $.Release.Service }}
  annotations:
    kubernetes.io/ingress.class: traefik
spec:
  rules:
    - host: {{ .Values.hostname }}
      http:
        paths:
          - path: /api
            pathType: ImplementationSpecific
            backend:
              service: calculator-service
              port:
                number: 3333