apiVersion: v1
kind: Service
metadata:
  name: mortgage-service
spec:
  selector:
    app: mortgage-app
  type: NodePort 
  ports:
    - protocol: TCP
      port: 3334
      targetPort: 3334
      nodePort: 31001