apiVersion: apps/v1
kind: Deployment
metadata:
  name: calculator-deployment
spec:
  selector:
    matchLabels:
      app: calculator
  replicas: 2
  template:
    metadata:
      labels:
        app: calculator
    spec:
      containers:
        - name: calculator
          image: calculator-api
          ports:
            - containerPort: 3333
          imagePullPolicy: Never # Image should not be pulled