apiVersion: apps/v1
kind: Deployment
metadata:
  name: calculator-deployment
spec:
  selector:
    matchLabels:
      app: calculator
  replicas: 2
  template:
    metadata:
      labels:
        app: calculator
    spec:
      containers:
        - name: calculator
          image: calculator-api
          ports:
            - containerPort: 3333
          imagePullPolicy: Never # Image should not be pulled
          livenessProbe:
            httpGet:
              path: /api/health-check
              port: 3333
            initialDelaySeconds: 3
            periodSeconds: 3
            failureThreshold: 2
          env:
            - name: HEALTH_ID
              valueFrom:
                configMapKeyRef:
                  name: calculator-envs
                  key: healthId