apiVersion: v1
kind: Service
metadata:
  name: calculator-service
spec:
  selector:
    app: calculator
  type: LoadBalancer 
  ports:
    - protocol: TCP
      port: 3333
      targetPort: 3333
      nodePort: 31000