# This workflow will do a clean install of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Node.js CI

on:
  push:
    branches: [ '**' ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [14.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v2
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
    - run: npm ci
    - run: npm run postinstall
    - run: npm install -g nx
    - run: npm install codecov -g
    - name: Cache ESLint Result
      id: cache-eslint
      uses: actions/cache@v3
      env:
        cache-name: cache-eslint
      with:
        # npm cache file is stored on .eslintcache
        path: .eslintcache
        key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('.eslintcache') }}
    - if: ${{ steps.cache-eslint.outputs.cache-hit == 'true' }}
        name: ESlint cache was found
        continue-on-error: true
        run: echo "ESLINT Cache was found"
    - if: ${{ steps.cache-eslint.outputs.cache-hit != 'true' }}
        name: ESLint cache was NOT found
        continue-on-error: true
        run: echo "ESLINT Cache was NOT found"  
    - run: npm run lint:all
    - run: npm run test:all
    - run: codecov

